INSERT INTO bears (name, age, gender, color, temperament, alive)
  VALUES ("Mr. Chocolate", 2, "M", "Brown", "Aloof", FALSE)
INSERT INTO bears (name, age, gender, color, temperament, alive)
  VALUES ("Rowdy", 6, "NB", "Purple", "Standoffish", TRUE)
INSERT INTO bears (name, age, gender, color, temperament, alive)
  VALUES ("Tabitha", 234, "F", "Pink", "Happy", TRUE)
INSERT INTO bears (name, age, gender, color, temperament, alive)
  VALUES ("Sergeant Brown", 8,  )
INSERT INTO bears (name, age, gender, color, temperament, alive)
  VALUES ("Melissa", 12, "TF", "Black", "Intrigued", TRUE)
INSERT INTO bears (name, age, gender, color, temperament, alive)
  VALUES ("Grinch", 6, "F", "Black", "Ironically Kind", TRUE)
INSERT INTO bears (name, age, gender, color, temperament, alive)
  VALUES ("Wendy", 3, "F", "Aquamarine", "There For You", TRUE)
INSERT INTO bears (name, age, gender, color, temperament, alive)
  VALUES (NULL, 6, "M", "Tan", "Truly Outrageous", FALSE)
